[project]
name = "algoritmos-de-ordenamiento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipdb>=0.13.13",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
